# Generated by Django 4.2 on 2023-04-06 13:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration( migrations.Migration ):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("name", models.CharField( max_length=100 )),
                ("slug", models.SlugField()),
                ("created", models.DateTimeField( auto_now_add=True )),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("title", models.CharField( max_length=100 )),
                ("slug", models.SlugField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="project_images/default.jpg",
                        null=True,
                        upload_to="project_images",
                    ),
                ),
                ("description", models.TextField( blank=True, null=True )),
                ("total_votes", models.IntegerField( blank=True, default=0, null=True )),
                ("votes_ratio", models.IntegerField( blank=True, default=0, null=True )),
                ("demo_link", models.CharField( blank=True, max_length=500, null=True )),
                (
                    "source_link",
                    models.CharField( blank=True, max_length=500, null=True ),
                ),
                ("created", models.DateTimeField( auto_now_add=True )),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
                ("tags", models.ManyToManyField( blank=True, to="projects.tag" )),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("body", models.TextField( blank=True, null=True )),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("up", "Положительная оценка"),
                            ("down", "Отрицательная оценка"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created", models.DateTimeField( auto_now_add=True )),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "project")},
            },
        ),
    ]
