# Generated by Django 4.2 on 2023-04-17 21:09

from django.db import migrations, models


class Migration( migrations.Migration ):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/project_images/default.jpg",
                null=True,
                upload_to="media/project_images",
            ),
        ),
    ]
