# Generated by Django 4.2 on 2023-04-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                default="project_images/default.jpg",
                null=True,
                upload_to="project_images",
                verbose_name="Изображение",
            ),
        ),
    ]
